server:
  port: 10010
spring:
  application:
    name: curves-account
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/curves-account?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1qaz@WSX
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.curves.service.account.services.pojo.entity
# pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
# eureka
eureka:
  client:
    service-url:
      defaultZone: http://curves:vicbaily528@127.0.0.1:9000/eureka/
    healthcheck:
      enabled: true